/** Small, dependency-free OpenAPI description for the stable HTTP surface. */
export const OPENAPI_DOCUMENT = {
  openapi: "3.1.0",
  info: {
    title: "小奕小说生成工具 API",
    version: "0.4.0",
    description: "账号制作者工作台 API。邀请码只用于注册，作者使用账号密码登录后获得 Bearer 会话令牌。",
  },
  servers: [{ url: "/" }],
  security: [{ bearerAuth: [] }],
  paths: {
    "/api/health": { get: { summary: "存活探针", security: [] } },
    "/api/ready": { get: { summary: "就绪探针", security: [] } },
    "/api/auth/register": { post: { summary: "使用邀请码注册账号", security: [] } },
    "/api/auth/login": { post: { summary: "账号登录", security: [] } },
    "/api/auth/logout": { post: { summary: "退出当前账号会话" } },
    "/api/providers": { get: { summary: "Provider 目录" } },
    "/api/providers/models": { post: { summary: "拉取兼容端点模型列表" } },
    "/api/providers/test": { post: { summary: "测试 Provider 连接" } },
    "/api/books": {
      get: { summary: "列出作品" },
      post: { summary: "创建作品并生成方向" },
    },
    "/api/books/recoverable": { get: { summary: "读取可恢复作品 ID" } },
    "/api/books/recoverable/details": { get: { summary: "读取可恢复作品详情" } },
    "/api/usage": { get: { summary: "读取当前周期模型 Token 与费用用量" } },
    "/api/books/{bookId}": { get: { summary: "读取作品详情" } },
    "/api/books/{bookId}/directions": { get: { summary: "读取方向候选" } },
    "/api/books/{bookId}/chapters": { get: { summary: "读取卷章计划与已采纳正文" } },
    "/api/books/{bookId}/timeline/{planId}": { patch: { summary: "按作品 revision 修改故事时间线" } },
    "/api/books/{bookId}/timeline": { patch: { summary: "批量修改故事时间线" } },
    "/api/books/{bookId}/timeline/reorder": { post: { summary: "安全重排未采纳章节" } },
    "/api/books/{bookId}/timeline/preview": { post: { summary: "生成 AI 时间线差异预览" } },
    "/api/books/{bookId}/search": { get: { summary: "搜索作品资料、章纲和正文" } },
    "/api/books/{bookId}/consistency": { get: { summary: "检查人物、地点、时间线和伏笔一致性" } },
    "/api/books/{bookId}/directions/{directionId}/select": { post: { summary: "选择方向并生成设定章纲" } },
    "/api/books/{bookId}/production": { post: { summary: "启动正文生产" } },
    "/api/production-runs/{runId}": { get: { summary: "读取生产进度" } },
    "/api/production-runs/{runId}/pause": { post: { summary: "暂停生产" } },
    "/api/production-runs/{runId}/resume": { post: { summary: "恢复生产" } },
    "/api/production-runs/{runId}/cancel": { post: { summary: "取消生产" } },
    "/api/production-runs/{runId}/rewrite": { post: { summary: "重写当前章节" } },
    "/api/chapter-candidates/{candidateId}": { get: { summary: "读取候选" } },
    "/api/chapter-candidates/{candidateId}/accept": { post: { summary: "原子采纳候选" } },
    "/api/chapter-candidates/{candidateId}/discard": { post: { summary: "丢弃候选" } },
    "/api/books/{bookId}/export": { post: { summary: "导出正文" } },
    "/api/books/{bookId}/memory": { get: { summary: "读取长篇记忆" } },
    "/api/books/{bookId}/memory/context/{chapterNumber}": { get: { summary: "预览记忆上下文" } },
    "/api/admin/metrics": { get: { summary: "JSON 运维指标" } },
    "/api/admin/providers": { get: { summary: "服务端 Provider 配置摘要" } },
    "/api/admin/providers/{providerIndex}/models": { get: { summary: "拉取服务端 Provider 模型列表" } },
    "/api/admin/providers/{providerIndex}/test": { post: { summary: "测试服务端 Provider 连接" } },
    "/api/admin/runs": { get: { summary: "搜索生产任务与失败原因" } },
    "/api/admin/audit": { get: { summary: "审计日志" } },
    "/api/admin/usage": { get: { summary: "用量与成本" } },
    "/api/admin/backups": { get: { summary: "备份状态" }, post: { summary: "创建备份" } },
    "/api/admin/backups/verify": { post: { summary: "校验备份" } },
    "/api/admin/invitations": {
      get: { summary: "列出邀请码" },
      post: { summary: "创建邀请码" },
    },
    "/api/admin/invitations/{invitationId}/revoke": { post: { summary: "撤销邀请码" } },
  },
  components: {
    securitySchemes: {
      bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "token" },
    },
  },
} as const;
