export const AUTO_NOVEL_CHANNELS = {
  booksList: "auto-novel:books-list",
  booksRecoverableList: "auto-novel:books-recoverable-list",
  booksRecoverableDetails: "auto-novel:books-recoverable-details",
  booksCreate: "auto-novel:books-create",
  booksGet: "auto-novel:books-get",
  timelineUpdate: "auto-novel:timeline-update",
  timelineBatchUpdate: "auto-novel:timeline-batch-update",
  timelineReorder: "auto-novel:timeline-reorder",
  timelinePreview: "auto-novel:timeline-preview",
  authoringSearch: "auto-novel:authoring-search",
  authoringConsistency: "auto-novel:authoring-consistency",
  usageSummary: "auto-novel:usage-summary",
  booksChapters: "auto-novel:books-chapters",
  directionsList: "auto-novel:directions-list",
  directionsSelect: "auto-novel:directions-select",
  productionStart: "auto-novel:production-start",
  productionGet: "auto-novel:production-get",
  productionPause: "auto-novel:production-pause",
  productionResume: "auto-novel:production-resume",
  productionRewrite: "auto-novel:production-rewrite",
  productionCancel: "auto-novel:production-cancel",
  candidateAccept: "auto-novel:candidate-accept",
  candidateGet: "auto-novel:candidate-get",
  candidateDiscard: "auto-novel:candidate-discard",
  booksExport: "auto-novel:books-export",
  memoryList: "auto-novel:memory-list",
  memoryContext: "auto-novel:memory-context",
  memoryHistory: "auto-novel:memory-history",
  memoryUpdate: "auto-novel:memory-update",
  memoryRefresh: "auto-novel:memory-refresh",
  memoryRollback: "auto-novel:memory-rollback",
  candidateMemoryReview: "auto-novel:candidate-memory-review",
  candidateTextUpdate: "auto-novel:candidate-text-update",
} as const;

export type AutoNovelDesktopChannel =
  (typeof AUTO_NOVEL_CHANNELS)[keyof typeof AUTO_NOVEL_CHANNELS];
