export const AUTO_NOVEL_CHANNELS = {
  booksList: "auto-novel:books-list",
  booksRecoverableList: "auto-novel:books-recoverable-list",
  booksRecoverableDetails: "auto-novel:books-recoverable-details",
  booksRuns: "auto-novel:books-runs",
  booksSnapshotsList: "auto-novel:books-snapshots-list",
  booksSnapshotCreate: "auto-novel:books-snapshot-create",
  booksSnapshotDelete: "auto-novel:books-snapshot-delete",
  booksSnapshotRestore: "auto-novel:books-snapshot-restore",
  booksRevisionsList: "auto-novel:books-revisions-list",
  booksRevisionDiff: "auto-novel:books-revision-diff",
  booksRevisionRestore: "auto-novel:books-revision-restore",
  booksRevisionMerge: "auto-novel:books-revision-merge",
  authoringWorkspaceGet: "auto-novel:authoring-workspace-get",
  authoringWorkspaceSave: "auto-novel:authoring-workspace-save",
  authorDeliveryGet: "auto-novel:author-delivery-get",
  authorDeliverySave: "auto-novel:author-delivery-save",
  booksCreate: "auto-novel:books-create",
  booksGet: "auto-novel:books-get",
  timelineUpdate: "auto-novel:timeline-update",
  timelineBatchUpdate: "auto-novel:timeline-batch-update",
  timelineReorder: "auto-novel:timeline-reorder",
  timelinePreview: "auto-novel:timeline-preview",
  authoringSearch: "auto-novel:authoring-search",
  authoringConsistency: "auto-novel:authoring-consistency",
  authoringQualityGate: "auto-novel:authoring-quality-gate",
  booksQuota: "auto-novel:books-quota",
  booksAutomationExecutions: "auto-novel:books-automation-executions",
  authoringReplace: "auto-novel:authoring-replace",
  authoringImport: "auto-novel:authoring-import",
  usageSummary: "auto-novel:usage-summary",
  booksChapters: "auto-novel:books-chapters",
  directionsList: "auto-novel:directions-list",
  directionsSelect: "auto-novel:directions-select",
  productionStart: "auto-novel:production-start",
  productionGet: "auto-novel:production-get",
  productionPause: "auto-novel:production-pause",
  productionResume: "auto-novel:production-resume",
  productionRewrite: "auto-novel:production-rewrite",
  productionCancel: "auto-novel:production-cancel",
  candidateAccept: "auto-novel:candidate-accept",
  candidateGet: "auto-novel:candidate-get",
  candidateDiscard: "auto-novel:candidate-discard",
  booksExport: "auto-novel:books-export",
  memoryList: "auto-novel:memory-list",
  memoryContext: "auto-novel:memory-context",
  memoryHistory: "auto-novel:memory-history",
  memoryUpdate: "auto-novel:memory-update",
  memoryRefresh: "auto-novel:memory-refresh",
  memoryRollback: "auto-novel:memory-rollback",
  candidateMemoryReview: "auto-novel:candidate-memory-review",
  candidateTextUpdate: "auto-novel:candidate-text-update",
} as const;

export type AutoNovelDesktopChannel =
  (typeof AUTO_NOVEL_CHANNELS)[keyof typeof AUTO_NOVEL_CHANNELS];
