export const DESKTOP_CHANNELS = {
  workspaceGet: "workspace:get",
  projectCreate: "project:create",
  chapterCreate: "chapter:create",
  chapterUpdate: "chapter:update",
  providerList: "provider:list",
  providerListModels: "provider:list-models",
  providerTestConnection: "provider:test-connection",
  providerGetSettings: "provider:get-settings",
  providerSaveSettings: "provider:save-settings",
  providerGetWorkflowSettings: "provider:get-workflow-settings",
  providerSaveWorkflowSettings: "provider:save-workflow-settings",
  providerClearKey: "provider:clear-key",
  authActivationStatus: "auth:activation-status",
  authActivate: "auth:activate",
  authRegister: "auth:register",
  authLogin: "auth:login",
  authLogout: "auth:logout",
  databaseStatus: "database:status",
  databaseImport: "database:import",
  databasePreviewImport: "database:preview-import",
  databaseConfirmImport: "database:confirm-import",
  databaseCancelImport: "database:cancel-import",
  databaseExport: "database:export",
  databaseExportEncrypted: "database:export-encrypted",
  lifecycleResolveClose: "lifecycle:resolve-close",
  lifecycleCommand: "lifecycle:command",
} as const;

export type DesktopChannel = (typeof DESKTOP_CHANNELS)[keyof typeof DESKTOP_CHANNELS];
